name: pushing Docker image to ecr
on:
  push:
    branches: [ main ]
  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  IMAGE_TAG: sample_image

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configuring AWS credentials

      
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: python
          IMAGE_TAG: sample_image
        run: |
         
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/a4i5r6b0 
          docker build -t python .
          docker tag python:latest public.ecr.aws/a4i5r6b0/python:latest
          #docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push public.ecr.aws/a4i5r6b0/python:latest